//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GadisItalia {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GadisItalia.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altre Caratteristiche.
        /// </summary>
        internal static string AltreCaratteristiche {
            get {
                return ResourceManager.GetString("AltreCaratteristiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caratteristiche.
        /// </summary>
        internal static string Caratteristiche {
            get {
                return ResourceManager.GetString("Caratteristiche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Postale.
        /// </summary>
        internal static string CodicePostale {
            get {
                return ResourceManager.GetString("CodicePostale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codice Tipo Fornitore.
        /// </summary>
        internal static string CodTipoFornitore {
            get {
                return ResourceManager.GetString("CodTipoFornitore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comune Destinazione.
        /// </summary>
        internal static string ComuneDestinazione {
            get {
                return ResourceManager.GetString("ComuneDestinazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione.
        /// </summary>
        internal static string Descrizione {
            get {
                return ResourceManager.GetString("Descrizione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrizione Logistica.
        /// </summary>
        internal static string DescrizioneLogistica {
            get {
                return ResourceManager.GetString("DescrizioneLogistica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        internal static string Extra {
            get {
                return ResourceManager.GetString("Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag Attivo.
        /// </summary>
        internal static string FlagAttivo {
            get {
                return ResourceManager.GetString("FlagAttivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornitore.
        /// </summary>
        internal static string Fornitore {
            get {
                return ResourceManager.GetString("Fornitore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha Lamentele.
        /// </summary>
        internal static string HaLamentele {
            get {
                return ResourceManager.GetString("HaLamentele", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImmaginePreferita.
        /// </summary>
        internal static string ImmaginePreferita {
            get {
                return ResourceManager.GetString("ImmaginePreferita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immagini.
        /// </summary>
        internal static string Immagini {
            get {
                return ResourceManager.GetString("Immagini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indirizzo.
        /// </summary>
        internal static string Indirizzo {
            get {
                return ResourceManager.GetString("Indirizzo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informazioni sul fornitore.
        /// </summary>
        internal static string InformazioniSulFornitore {
            get {
                return ResourceManager.GetString("InformazioniSulFornitore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localizzazione.
        /// </summary>
        internal static string Localizzazione {
            get {
                return ResourceManager.GetString("Localizzazione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nota.
        /// </summary>
        internal static string Nota {
            get {
                return ResourceManager.GetString("Nota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ragione Sociale.
        /// </summary>
        internal static string RagioneSociale {
            get {
                return ResourceManager.GetString("RagioneSociale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsabile.
        /// </summary>
        internal static string Responsabile {
            get {
                return ResourceManager.GetString("Responsabile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitoweb.
        /// </summary>
        internal static string Sitoweb {
            get {
                return ResourceManager.GetString("Sitoweb", resourceCulture);
            }
        }
    }
}
